### ISSUE TITLE
期末考试题的4应该选B吧

### ISSUE THREAD

**Issue by xuuuyp** [southernEast/SEU_553#1]
不是基类对象不可以赋值给派生类吗

**Comment by southernEast** [comment]
没错，是选B，派生类对象可以当成基类对象使用，基类指针或引用也可以绑定到派生类对象中的基类部分上。（对了，那几个PDF中的答案有一些是有错误的，那些答案是拿到PDF的时候就有的，所以没有更改过来，不好意思。）
