### ISSUE TITLE
期末考试题第九题的A项

### ISSUE THREAD

**Issue by aaa1999** [southernEast/SEU_553#2]
![image](https://user-images.githubusercontent.com/49224989/157204265-f9e1daad-ee21-488d-8466-7cb1f9ab7aa1.png)
答案选c，但是我感觉a也错了。

我记得好像是类内实现的成员函数才是inline的。
请大家指教。

**Comment by aaa1999** [comment]
不开新的issue了。
期末考试的第12题

![image](https://user-images.githubusercontent.com/49224989/157205140-00fa30fd-74c8-4562-bc42-d235e1254c3f.png)
这个为什么错了呀。

**Comment by southernEast** [comment]
> ![image](https://user-images.githubusercontent.com/49224989/157204265-f9e1daad-ee21-488d-8466-7cb1f9ab7aa1.png) 答案选c，但是我感觉a也错了。
> 
> 我记得好像是类内实现的成员函数才是inline的。 请大家指教。

第9题的A确实是不正确的，而且C是正确的，答案错了，这个PDF中的答案没有修改，有一些错误，这道题应该选A。

**Comment by southernEast** [comment]
> 不开新的issue了。 期末考试的第12题
> 
> ![image](https://user-images.githubusercontent.com/49224989/157205140-00fa30fd-74c8-4562-bc42-d235e1254c3f.png) 这个为什么错了呀。

第12题的选项都模棱两可，其实都可以算是正确的，这样这道题就没有答案，但就我个人感觉的话，如果硬要选一个可以揪D，“C++中‘有’指向对象的指针”而不是“C++‘可以有’指向对象的指针”😜，你觉得呢？

**Comment by aaa1999** [comment]
哦哦，我懂了。谢谢回答。
